spring.application.name=awesome-pizza

spring.datasource.url=jdbc:h2:mem:awesomepizza;DB_CLOSE_DELAY=-1
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
